### ISSUE TITLE
Some exception  

### ISSUE THREAD

**Issue by dhru18** [sitepoint-editors/Android-VideoTube#1]
Gradle sync started
Gradle sync completed
Executing tasks: [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
Gradle build finished in 24s 788ms
UnsupportedMethodException
           Unsupported method: AndroidProject.getPluginGeneration().
           The version of Gradle you connect to does not support that method.
           To resolve the problem you can change/upgrade the target version of Gradle you connect to.
           Alternatively, you can ignore this exception and read other information from the model.
UnsupportedMethodException
           Unsupported method: AndroidProject.getPluginGeneration().
           The version of Gradle you connect to does not support that method.
           To resolve the problem you can change/upgrade the target version of Gradle you connect to.
           Alternatively, you can ignore this exception and read other information from the model.

**Comment by echessa** [comment]
I've just updated the code and post on SitePoint, so it should run okay now.

**Comment by arielelkin** [comment]
closed via https://github.com/sitepoint-editors/Android-VideoTube/pull/2
